// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnrdpuvbwicahzcpxdkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ucmRwdXZid2ljYWh6Y3B4ZGt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1OTUzODgsImV4cCI6MjA3NzE3MTM4OH0.pJj6gXJUEkHbITjsAte2MHpQyTSo9GX4en3uAli-e8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});